name: Terraform Apply and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract image names
        run: |
          repositories=()
          while IFS= read -r line; do
            # Get image name without tag, replace '/' and ':' to '-'
            name=$(echo "$line" | cut -d':' -f1 | tr '/:' '-')
            repositories+=("\"$name\"")
          done < docker-images.txt
          echo "repositories = [${repositories[*]}]" > terraform/terraform.tfvars
          echo "REPO_LIST=${repositories[*]}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Pull and Push Docker Images
        run: |
          while IFS= read -r line; do
            image=$line
            name=$(echo "$line" | cut -d':' -f1 | tr '/:' '-')
            tag=$(echo "$line" | cut -d':' -f2)
            ecr_repo="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${name}"
            docker pull $image
            docker tag $image "$ecr_repo:$tag"
            docker push "$ecr_repo:$tag"
          done < docker-images.txt
